-- gg

union all
select /*+FULL(A) FULL(F) PARALLEL(4) */
A.CLOS_YR_MON AS CLS_YM
#{actgSepCd}  AS ACTG_SEP_CD
, A.ACTCD AS POLINO
, A.ACTCD AS  ACT_CD
, NVL(B.SAP_DEPT, a.DEPT_COD) AS ORGZ_CD
~~~ABS

FROM ACC_SUM_IFRS A
, (SELECT A.DEPT_COD
, A.DEPT_NAM
, A.SAP_DEPT
FROM ACCSAPDEPT_HISTORY A
, (SELECT A.DEPT_COD
, MIN(SEQ) AS SEQ
FROM ACCSAPDEPT_HISTORY A
WHERE TO_CHAR(A.Z_CREATE_DATE, 'YYYYMMDD')
<= TO_CHAR(LAST_DAT(TO_DATE(#{clsYm}, 'YYYYMM')), 'YYYYMMDD')
GROUP BY A.DEPT_COD
) B
WHERE B.DEPT_COD = A.DEPT_COD
AND B.SEQ = A.SEQ
)B
, (SELECT SUBSTR(A.KOSTL, 7,4),' ')) AS SCHD_ORGZ_CD
FROM ACC_SAP_BUDGET A
, (
  SELECT SUBSTR(A.KOSTL, 7,4) AS ORGZ_CD
  , MAX(AMOUNT1) AS AMT
  FROM ACC_SAP_BUDGET A
  WHERE A.MGYEAR||A.MGMONTH = #{clsYm}
  AND SUBSTR(A.ACTCD,3,8) = '53072200'
  AND A.AMOUNT1
  GROUP BY SUBSTR(A.KOSTL, 7, 4)
) b
WHERE A.MGYEAR||A.MGMONTH = ~~~
GROUP BY SUBSTR(A.KOSTL,7,4)
)C
, IFRBE010MC D
, IFRBE115MM E
